#pragma once
#include <iostream>
#include <Windows.h>
#include <stdint.h>
#include <Psapi.h>
#include <TlHelp32.h>
#include <winternl.h>
#include "defs.hpp"
#include "structures.hpp"
#include "functionPtrs.hpp"